# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='websearch2/proto/news_recommendation/rcm_queue/rcm_queue_rel_txt.proto',
  package='pb.rcm.queue.txt',
  serialized_pb='\nFwebsearch2/proto/news_recommendation/rcm_queue/rcm_queue_rel_txt.proto\x12\x10pb.rcm.queue.txt\x1a>websearch2/proto/news_recommendation/rcm_queue/rcm_queue.proto\"E\n\x11RelatedTxtRequest\x12\x0f\n\x07news_id\x18\x01 \x02(\x0c\x12\x0e\n\x03hot\x18\x02 \x01(\x05:\x01\x30\x12\x0f\n\x04type\x18\x03 \x01(\r:\x01\x30:P\n\x0brel_txt_req\x12\x15.pb.rcm.queue.Request\x18\x92N \x01(\x0b\x32#.pb.rcm.queue.txt.RelatedTxtRequest')


REL_TXT_REQ_FIELD_NUMBER = 10002
rel_txt_req = descriptor.FieldDescriptor(
  name='rel_txt_req', full_name='pb.rcm.queue.txt.rel_txt_req', index=0,
  number=10002, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_RELATEDTXTREQUEST = descriptor.Descriptor(
  name='RelatedTxtRequest',
  full_name='pb.rcm.queue.txt.RelatedTxtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='news_id', full_name='pb.rcm.queue.txt.RelatedTxtRequest.news_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hot', full_name='pb.rcm.queue.txt.RelatedTxtRequest.hot', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='pb.rcm.queue.txt.RelatedTxtRequest.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=156,
  serialized_end=225,
)

import websearch2.proto.news_recommendation.rcm_queue.rcm_queue_pb2


class RelatedTxtRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RELATEDTXTREQUEST
  
  # @@protoc_insertion_point(class_scope:pb.rcm.queue.txt.RelatedTxtRequest)

rel_txt_req.message_type = _RELATEDTXTREQUEST
websearch2.proto.news_recommendation.rcm_queue.rcm_queue_pb2.Request.RegisterExtension(rel_txt_req)
# @@protoc_insertion_point(module_scope)
