# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='websearch2/proto/news_recommendation/rcm_queue/rcm_queue_common.proto',
  package='pb.rcm.queue',
  serialized_pb='\nEwebsearch2/proto/news_recommendation/rcm_queue/rcm_queue_common.proto\x12\x0cpb.rcm.queue\"\xe8\x01\n\x0bUserProfile\x12\x15\n\rdevice_id_md5\x18\x01 \x01(\x04\x12\x0b\n\x03\x61ge\x18\x02 \x01(\r\x12\x0b\n\x03sex\x18\x03 \x01(\r\x12\x13\n\x0bsession_num\x18\x04 \x01(\r\x12\x18\n\x10today_show_count\x18\x05 \x01(\r\x12\x12\n\nshow_count\x18\x06 \x01(\r\x12\x11\n\ttoday_ctr\x18\x07 \x01(\x02\x12\x0b\n\x03\x63tr\x18\x08 \x01(\x02\x12\n\n\x02ip\x18\t \x01(\x0c\x12\x17\n\x0ftx_lbs_loc_city\x18\n \x01(\x0c\x12 \n\x18user_channel_click_score\x18\x0b \x01(\r')




_USERPROFILE = descriptor.Descriptor(
  name='UserProfile',
  full_name='pb.rcm.queue.UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='device_id_md5', full_name='pb.rcm.queue.UserProfile.device_id_md5', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age', full_name='pb.rcm.queue.UserProfile.age', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sex', full_name='pb.rcm.queue.UserProfile.sex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_num', full_name='pb.rcm.queue.UserProfile.session_num', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='today_show_count', full_name='pb.rcm.queue.UserProfile.today_show_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='show_count', full_name='pb.rcm.queue.UserProfile.show_count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='today_ctr', full_name='pb.rcm.queue.UserProfile.today_ctr', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctr', full_name='pb.rcm.queue.UserProfile.ctr', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='pb.rcm.queue.UserProfile.ip', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tx_lbs_loc_city', full_name='pb.rcm.queue.UserProfile.tx_lbs_loc_city', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_channel_click_score', full_name='pb.rcm.queue.UserProfile.user_channel_click_score', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=320,
)



class UserProfile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERPROFILE
  
  # @@protoc_insertion_point(class_scope:pb.rcm.queue.UserProfile)

# @@protoc_insertion_point(module_scope)
